/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemestersRouteImport } from './routes/semesters'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GpaCalculatorRouteImport } from './routes/gpa-calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GradeCalculatorIndexRouteImport } from './routes/grade-calculator/index'
import { Route as GradeCalculatorCourseIdRouteImport } from './routes/grade-calculator/$courseId'

const SemestersRoute = SemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GpaCalculatorRoute = GpaCalculatorRouteImport.update({
  id: '/gpa-calculator',
  path: '/gpa-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradeCalculatorIndexRoute = GradeCalculatorIndexRouteImport.update({
  id: '/grade-calculator/',
  path: '/grade-calculator/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradeCalculatorCourseIdRoute = GradeCalculatorCourseIdRouteImport.update({
  id: '/grade-calculator/$courseId',
  path: '/grade-calculator/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/profile': typeof ProfileRoute
  '/semesters': typeof SemestersRoute
  '/grade-calculator/$courseId': typeof GradeCalculatorCourseIdRoute
  '/grade-calculator/': typeof GradeCalculatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/profile': typeof ProfileRoute
  '/semesters': typeof SemestersRoute
  '/grade-calculator/$courseId': typeof GradeCalculatorCourseIdRoute
  '/grade-calculator': typeof GradeCalculatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/profile': typeof ProfileRoute
  '/semesters': typeof SemestersRoute
  '/grade-calculator/$courseId': typeof GradeCalculatorCourseIdRoute
  '/grade-calculator/': typeof GradeCalculatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gpa-calculator'
    | '/profile'
    | '/semesters'
    | '/grade-calculator/$courseId'
    | '/grade-calculator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gpa-calculator'
    | '/profile'
    | '/semesters'
    | '/grade-calculator/$courseId'
    | '/grade-calculator'
  id:
    | '__root__'
    | '/'
    | '/gpa-calculator'
    | '/profile'
    | '/semesters'
    | '/grade-calculator/$courseId'
    | '/grade-calculator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GpaCalculatorRoute: typeof GpaCalculatorRoute
  ProfileRoute: typeof ProfileRoute
  SemestersRoute: typeof SemestersRoute
  GradeCalculatorCourseIdRoute: typeof GradeCalculatorCourseIdRoute
  GradeCalculatorIndexRoute: typeof GradeCalculatorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/semesters': {
      id: '/semesters'
      path: '/semesters'
      fullPath: '/semesters'
      preLoaderRoute: typeof SemestersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpa-calculator': {
      id: '/gpa-calculator'
      path: '/gpa-calculator'
      fullPath: '/gpa-calculator'
      preLoaderRoute: typeof GpaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-calculator/': {
      id: '/grade-calculator/'
      path: '/grade-calculator'
      fullPath: '/grade-calculator/'
      preLoaderRoute: typeof GradeCalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-calculator/$courseId': {
      id: '/grade-calculator/$courseId'
      path: '/grade-calculator/$courseId'
      fullPath: '/grade-calculator/$courseId'
      preLoaderRoute: typeof GradeCalculatorCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GpaCalculatorRoute: GpaCalculatorRoute,
  ProfileRoute: ProfileRoute,
  SemestersRoute: SemestersRoute,
  GradeCalculatorCourseIdRoute: GradeCalculatorCourseIdRoute,
  GradeCalculatorIndexRoute: GradeCalculatorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
